// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuE4Qt9Iuhs__xnsrFRSS360oGVUGjHMY',
    appId: '1:859283388278:web:b9f98a76aea38153106c57',
    messagingSenderId: '859283388278',
    projectId: 'ferry-f30a0',
    authDomain: 'ferry-f30a0.firebaseapp.com',
    storageBucket: 'ferry-f30a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc6iG1eaipavQ2Q2OsQfub6AnmRuv9ees',
    appId: '1:859283388278:android:6a6b9fa1abecf95f106c57',
    messagingSenderId: '859283388278',
    projectId: 'ferry-f30a0',
    storageBucket: 'ferry-f30a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7R1ET5OJaY7bHxRm9UteTxREuDClYO4c',
    appId: '1:859283388278:ios:174c06e351e488be106c57',
    messagingSenderId: '859283388278',
    projectId: 'ferry-f30a0',
    storageBucket: 'ferry-f30a0.appspot.com',
    iosBundleId: 'com.example.tutorFirebase',
  );
}
